name: Bicep to ARM converter

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Converting
    runs-on: ubuntu-latest
    steps:
    - name: bicep-build-output
      uses: Azure/bicep-build-action@v1.0.1
      with:
        # Bicep main file path
        bicepFilePath: '/ADDS with Windows Clients/main.bicep'
        # ARM template output path
        outputFilePath: '/ADDS with Windows Clients/azuredeploy.json'
