name: Bicep to ARM converter

on:
  push:
    paths:
      - 'active-directory-with-windows-client/main.bicep'

jobs:
  build:
    name: Converting
    runs-on: ubuntu-latest
    steps:
    - name: bicep-build-output
      uses: Azure/bicep-build-action@v1.0.1
      with:
        # Bicep main file path
        bicepFilePath: './active-directory-with-windows-client/main.bicep'
        # ARM template output path
        outputFilePath: ./azuredeploy.json
